[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.7"
[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.7"
# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"
